# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import task_service_pb2 as task__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in task_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """Task execution service for FunnelCloud agents
    All calls require mTLS with CA-pinned certificates
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/funnelcloud.TaskService/Execute',
                request_serializer=task__service__pb2.TaskRequest.SerializeToString,
                response_deserializer=task__service__pb2.TaskResult.FromString,
                _registered_method=True)
        self.ExecuteStreaming = channel.unary_stream(
                '/funnelcloud.TaskService/ExecuteStreaming',
                request_serializer=task__service__pb2.TaskRequest.SerializeToString,
                response_deserializer=task__service__pb2.TaskOutput.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/funnelcloud.TaskService/GetStatus',
                request_serializer=task__service__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=task__service__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/funnelcloud.TaskService/Cancel',
                request_serializer=task__service__pb2.CancelRequest.SerializeToString,
                response_deserializer=task__service__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/funnelcloud.TaskService/Ping',
                request_serializer=task__service__pb2.PingRequest.SerializeToString,
                response_deserializer=task__service__pb2.PingResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """Task execution service for FunnelCloud agents
    All calls require mTLS with CA-pinned certificates
    """

    def Execute(self, request, context):
        """Execute a task on this agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStreaming(self, request, context):
        """Execute a task with streaming output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get the status of a running task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Cancel a running task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping to verify connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=task__service__pb2.TaskRequest.FromString,
                    response_serializer=task__service__pb2.TaskResult.SerializeToString,
            ),
            'ExecuteStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteStreaming,
                    request_deserializer=task__service__pb2.TaskRequest.FromString,
                    response_serializer=task__service__pb2.TaskOutput.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=task__service__pb2.TaskStatusRequest.FromString,
                    response_serializer=task__service__pb2.TaskStatusResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=task__service__pb2.CancelRequest.FromString,
                    response_serializer=task__service__pb2.CancelResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=task__service__pb2.PingRequest.FromString,
                    response_serializer=task__service__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'funnelcloud.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('funnelcloud.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Task execution service for FunnelCloud agents
    All calls require mTLS with CA-pinned certificates
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/funnelcloud.TaskService/Execute',
            task__service__pb2.TaskRequest.SerializeToString,
            task__service__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/funnelcloud.TaskService/ExecuteStreaming',
            task__service__pb2.TaskRequest.SerializeToString,
            task__service__pb2.TaskOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/funnelcloud.TaskService/GetStatus',
            task__service__pb2.TaskStatusRequest.SerializeToString,
            task__service__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/funnelcloud.TaskService/Cancel',
            task__service__pb2.CancelRequest.SerializeToString,
            task__service__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/funnelcloud.TaskService/Ping',
            task__service__pb2.PingRequest.SerializeToString,
            task__service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
