# Class 0: NOT SAVE - Casual conversation, general questions

CASUAL_EXAMPLES = [
    # Greetings and small talk
    "Hello",
    "Hi there",
    "Hey",
    "Good morning",
    "How are you?",
    "How are you doing?",
    "What's up?",
    "How's it going?",
    "Nice to meet you",
    "Thanks",
    "Thank you",
    "You're welcome",
    "Goodbye",
    "See you later",
    "Take care",
    "Hey AJ",
    "Yo",
    "Howdy",
    "Good evening",
    "Good afternoon",
    "What's happening?",
    "Long time no see",
    "Nice talking to you",
    "Cheers",
    "Later",
    "Peace",
    "Ciao",
    "Catch you later",
    "Have a good one",
    "Talk soon",
    
    # General questions (not about stored info)
    "What's the weather like?",
    "What time is it?",
    "What day is it?",
    "Can you help me?",
    "What can you do?",
    "Tell me a joke",
    "Tell me a story",
    "What do you think about AI?",
    "How does this work?",
    "What's the capital of France?",
    "Who wrote Romeo and Juliet?",
    "What's 2 plus 2?",
    "Explain quantum physics",
    "Write me a poem",
    "Help me with my code",
    "Debug this function",
    "What's the best programming language?",
    "How do I learn Python?",
    "What's for dinner?",
    "Should I go outside?",
    "Is it going to rain?",
    "What movie should I watch?",
    "Recommend a book",
    "What's trending?",
    "Tell me the news",
    
    # Conceptual questions (not file operations)
    "What is recursion?",
    "Explain polymorphism",
    "What's the difference between HTTP and HTTPS?",
    "How does git branching work?",
    "What is a REST API?",
    "Explain microservices architecture",
    "What is Docker?",
    "How does Kubernetes work?",
    "What's the difference between SQL and NoSQL?",
    "Explain SOLID principles",
    "What is dependency injection?",
    "How does OAuth work?",
    "What is a JWT token?",
    "Explain the CAP theorem",
    "What is event-driven architecture?",
    "How does async/await work?",
    "What's the difference between threads and processes?",
    "Explain TCP vs UDP",
    "What is a design pattern?",
    "How does garbage collection work?",
    "What is WebAssembly?",
    "Explain serverless computing",
    "What is CI/CD?",
    "How does load balancing work?",
    "What is caching?",
    "Explain database indexing",
    "What is a message queue?",
    "How does SSL/TLS work?",
    "What is rate limiting?",
    "Explain the singleton pattern",
    
    # Emotional expressions (not save requests)
    "I'm feeling tired",
    "I'm so happy today",
    "This is frustrating",
    "I'm confused",
    "That's interesting",
    "I don't understand",
    "Can you clarify?",
    "I'm not sure about that",
    "That makes sense",
    "I agree",
    "I disagree",
    "Maybe",
    "I think so",
    "Probably not",
    "Let me think about it",
    "This is great",
    "That's awesome",
    "I love it",
    "This is annoying",
    "I'm stuck",
    "I need help",
    "I'm lost",
    "That's confusing",
    "Oh I see",
    "Got it",
    "Makes sense now",
    "I was wrong",
    "My bad",
    "Never mind",
    "Forget it",
    
    # Task requests (not save requests)
    "Summarize this article",
    "Translate this to Spanish",
    "Fix this bug",
    "Optimize this code",
    "Write an email",
    "Draft a message",
    "Create a list",
    "Make a table",
    "Calculate this",
    "Analyze this data",
    "Compare these options",
    "Search for restaurants",
    "Find me a flight",
    "Book a hotel",
    "Set a timer",
    "Play some music",
    
    # Learning and explanation requests
    "Can you explain this?",
    "Teach me about Python",
    "How do I use this library?",
    "What's the best practice for this?",
    "Show me an example",
    "Walk me through this",
    "Break this down for me",
    "What does this mean?",
    "Why is this happening?",
    "What am I doing wrong?",
    "Help me understand",
    "Can you simplify this?",
    "ELI5 this concept",
    "What should I learn next?",
    "Where can I find documentation?",
    "Is there a tutorial for this?",
    "How do I get started?",
    "What are the prerequisites?",
    "What's the roadmap?",
    "Best resources to learn this?",
    
    # Opinion and advice
    "What do you recommend?",
    "Which one should I choose?",
    "Is this a good approach?",
    "What's your opinion?",
    "Am I on the right track?",
    "Does this look correct?",
    "Should I use this library?",
    "What framework do you suggest?",
    "Is this production ready?",
    "Any tips for this?",
    "What are common pitfalls?",
    "How can I improve this?",
    "What's the industry standard?",
    "Is this considered best practice?",
    "What would you do differently?",
    
    # Meta and conversational
    "What are you?",
    "Are you an AI?",
    "Who made you?",
    "What's your name?",
    "Can you think?",
    "Do you have feelings?",
    "Are you sentient?",
    "What model are you?",
    "How were you trained?",
    "What are your limitations?",
    "Can you learn?",
    "Do you remember our conversations?",
    "What languages do you speak?",
    "Are you better than ChatGPT?",
    "What's special about you?",
]
