# Class 2: TASK - Requests requiring workspace/code/execution actions

TASK_EXAMPLES = [
    # =======================================================================
    # FILE/WORKSPACE OPERATIONS
    # =======================================================================
    
    # List files
    "List the files in my workspace",
    "Show me the files",
    "What files are in this folder?",
    "Can you list the contents of the directory?",
    "Display the workspace contents",
    "Show me what's in the aj folder",
    "List all Python files",
    "What's in the src directory?",
    "Show the folder structure",
    "List files in my project",
    "Can you show me the directory tree?",
    "What files do I have?",
    "Display the file list",
    "Show workspace structure",
    "List contents of this folder",
    "What's in my workspace?",
    "Show me the project files",
    "List everything in the current directory",
    "Can you display the files here?",
    "What files exist in this path?",
    
    # Read files
    "Read the README file",
    "Show me the contents of main.py",
    "Open the config file",
    "Display the source code",
    "Cat the log file",
    "View the dockerfile",
    "Read this file for me",
    "Show me what's in that file",
    "Print the contents of setup.py",
    "Can you read requirements.txt?",
    "Display the code in app.js",
    "Open and show me the file",
    "Read the package.json",
    "Show the file contents",
    "View the contents of this script",
    "What does this file contain?",
    "Read me the error log",
    "Show the configuration file",
    "Display the markdown file",
    "Can you open this file?",
    
    # Write/create files
    "Create a new file called test.py",
    "Write this to a file",
    "Save this code to main.py",
    "Create a README for me",
    "Make a new configuration file",
    "Write a script that does X",
    "Generate a dockerfile",
    "Create the missing init file",
    "Write this function to utils.py",
    "Save the output to a file",
    
    # =======================================================================
    # CODE EXECUTION
    # =======================================================================
    
    # Run code
    "Run this Python code",
    "Execute this script",
    "Run the test suite",
    "Execute main.py",
    "Run this function",
    "Can you run this code for me?",
    "Execute the build script",
    "Run the linter",
    "Execute this command",
    "Run pytest",
    "Execute npm install",
    "Run the development server",
    "Can you execute this?",
    "Run this snippet",
    "Execute the following code",
    "Run it and show me the output",
    "Execute this Python script",
    "Run the unit tests",
    "Execute this shell command",
    "Run this in PowerShell",
    
    # =======================================================================
    # CODE ANALYSIS/DEVELOPMENT
    # =======================================================================
    
    # Analyze code
    "Analyze this code",
    "Review this function",
    "Check this code for bugs",
    "Analyze the performance",
    "Look at this implementation",
    "Review my code",
    "Analyze the structure",
    "Check for errors in this",
    "Review the logic here",
    "Analyze this algorithm",
    
    # Debug/fix code
    "Debug this function",
    "Fix this bug",
    "Find the error in this code",
    "Debug why this fails",
    "Fix the syntax error",
    "Help me debug this",
    "Find the issue in this code",
    "Fix this broken function",
    "Debug the failing test",
    "Fix this exception",
    
    # Refactor/improve
    "Refactor this code",
    "Optimize this function",
    "Improve the performance",
    "Clean up this code",
    "Refactor for readability",
    "Optimize the algorithm",
    "Improve this implementation",
    "Make this code more efficient",
    "Refactor the class structure",
    "Optimize the database queries",
    
    # Generate/create code
    "Generate a function that sorts",
    "Create a class for user management",
    "Write a function to parse JSON",
    "Generate unit tests",
    "Create an API endpoint",
    "Write a script to process data",
    "Generate a database schema",
    "Create a React component",
    "Write the boilerplate code",
    "Generate the missing methods",
    
    # Search code
    "Find all usages of this function",
    "Search for TODO comments",
    "Find where this is defined",
    "Search the codebase for errors",
    "Find all imports of this module",
    "Search for deprecated functions",
    "Find references to this class",
    "Search for hardcoded values",
    "Find all API calls",
    "Search for security issues",
    
    # =======================================================================
    # BUILD/DEPLOY OPERATIONS
    # =======================================================================
    
    "Build the project",
    "Deploy to production",
    "Compile the code",
    "Build the Docker image",
    "Deploy the application",
    "Package the release",
    "Build and run",
    "Compile TypeScript",
    "Build the frontend",
    "Deploy to staging",
    
    # =======================================================================
    # CALCULATIONS/PROCESSING
    # =======================================================================
    
    "Calculate the total",
    "Compute the average",
    "Process this data",
    "Convert this to JSON",
    "Parse this XML",
    "Transform this data",
    "Calculate the statistics",
    "Process the CSV file",
    "Convert formats",
    "Compute the hash",
    
    # =======================================================================
    # GIT/VERSION CONTROL
    # =======================================================================
    
    "Show git status",
    "List recent commits",
    "Check the git log",
    "Show the diff",
    "What changed in this commit?",
    "List branches",
    "Show uncommitted changes",
    "Check git history",
    "Display the blame",
    "Show merge conflicts",
    
    # =======================================================================
    # AFFIRMATIVE TASK CONTINUATIONS
    # =======================================================================
    # These are short responses that continue/confirm a task
    
    "Yes, do it",
    "Yes please",
    "Yes, go ahead",
    "Yeah, make those changes",
    "Yep, proceed",
    "Sure, do it",
    "Sure, go ahead",
    "Ok, make the changes",
    "Okay, proceed",
    "Go ahead",
    "Go ahead and do it",
    "Do it",
    "Make it so",
    "Proceed",
    "Proceed with the changes",
    "Continue",
    "Continue with that",
    "Let's do it",
    "Let's go",
    "Sounds good, do it",
    "That works, proceed",
    "Perfect, make those changes",
    "Great, go ahead",
    "All of them",
    "Do all of them",
    "All files",
    "Both",
    "Both options",
    "The first one",
    "The second one",
    "Option 1",
    "Option 2",
    "1",
    "2",
    "Commit it",
    "Save it",
    "Apply the changes",
    "Yes, apply that",
    
    # =======================================================================
    # WORKSPACE FOLLOW-UP QUESTIONS
    # =======================================================================
    # Questions about previously scanned/listed workspace data
    
    "How much space does it take up?",
    "How much disk space does it use?",
    "How big is it?",
    "What's the total size?",
    "Which files are largest?",
    "Which files take up the most space?",
    "What are the biggest files?",
    "Show me the largest files",
    "How many files are there?",
    "How many directories?",
    "What's in the layers folder?",
    "Tell me more about it",
    "Tell me more about those files",
    "Can you explain what those are?",
    "What do those files do?",
    "What is that file for?",
    "Why is it so big?",
    "Can I delete it?",
    "Can any of those be removed?",
    "Is it safe to delete?",
    "Which ones can I remove?",
    "What takes up the most space?",
    "Break down the space usage",
    "Show me a summary of the files",
    "Summarize what you found",
    "What did you find?",
    "What's interesting about it?",
    "Anything unusual?",
    "Are there any duplicates?",
    "Find duplicate files",
    "What about the other folders?",
    "And the tests folder?",
    "What's in there?",
    "How old are these files?",
    "When were they last modified?",
    "Show me recent changes",
    
    # =======================================================================
    # FOLLOW-UP ACTION REQUESTS
    # =======================================================================
    # Action requests that reference previous context
    
    "Can you do that?",
    "Can you change that?",
    "Can you fix that?",
    "Can you update that?",
    "Could you do that?",
    "Could you change it?",
    "Would you do that?",
    "Would you make that change?",
    "Please do that",
    "Please change it",
    "Please fix it",
    "Please update it",
    "Go through and change that",
    "Can you go through and do that?",
    "Change it to my name",
    "Change that to something else",
    "Update it please",
    "Fix it please",
    "Modify that",
    "Edit that",
    "Make that change",
    "Do the same for all files",
    "Apply that to all files",
    "Do that for everything",
    "Run it",
    "Execute it",
    "Try that",
    "Test it",
    
    # =======================================================================
    # REMOTE MACHINE / FUNNELCLOUD OPERATIONS
    # =======================================================================
    # Queries about remote machines, hardware status, system checks
    
    # Machine state queries
    "Is there a disc in the drive?",
    "Is there an optical disc loaded?",
    "Is there a CD in the drive?",
    "Is there a DVD loaded?",
    "What's in the disc drive?",
    "Check if there's a disc loaded",
    "Is the printer online?",
    "Is the printer connected?",
    "What printers are available?",
    "List connected devices",
    "What USB devices are connected?",
    "Is the external drive mounted?",
    "Check the hardware status",
    "What's the CPU usage?",
    "What's the memory usage?",
    "How much RAM is being used?",
    "What processes are running?",
    "Is the service running?",
    "Check if Docker is running",
    "Is the database running?",
    
    # Machine-specific queries (with machine names)
    "What's on ians-r16?",
    "Check ians-r16 for disc",
    "Is there a disc on ians-r16?",
    "What files are on ians-r16?",
    "Check the server status",
    "What's running on my PC?",
    "Check my computer for updates",
    "What's on my machine?",
    "List files on my desktop",
    "Check my downloads folder",
    "What's in my Documents?",
    "Scan my computer for large files",
    "What's using disk space on my PC?",
    "Check my system for errors",
    "What services are running on my machine?",
    "Is there anything in my recycle bin?",
    "Check my temp folder",
    "What's installed on my computer?",
    "List programs on my PC",
    "What software is installed?",
    
    # Remote execution requests
    "Run this on my machine",
    "Execute this on my PC",
    "Run a command on my computer",
    "Check something on my machine",
    "Do this on the remote machine",
    "Execute on the host",
    "Run remotely",
    "Check the remote system",
    
    # =======================================================================
    # FUNNELCLOUD AGENT DISCOVERY & STATUS
    # =======================================================================
    # Queries about agent availability, network discovery, and agent status
    
    # Agent discovery - general
    "Which agents are online?",
    "What agents are available?",
    "Show me the available agents",
    "List online agents",
    "Can you see which agents are online?",
    "What machines are connected?",
    "Show connected agents",
    "List all agents",
    "What agents do we have?",
    "Are there any agents online?",
    "How many agents are connected?",
    "Show agent status",
    "What agents can I use?",
    "Which machines are available?",
    "Discover available agents",
    "Find online agents",
    "Scan for agents",
    "What hosts are reachable?",
    "Show me the agent list",
    "List FunnelCloud agents",
    
    # Agent status queries
    "Is domain02 online?",
    "Is exchange01 available?",
    "Check if postfix01 is running",
    "Is my workstation connected?",
    "Is ians-r16 online?",
    "Can you reach domain02?",
    "Is the agent on domain02 responding?",
    "Check agent status on exchange01",
    "Is the FunnelCloud agent running on domain02?",
    "What's the status of domain02?",
    "Is domain02 reachable?",
    "Can you connect to exchange01?",
    
    # Agent capabilities
    "What can domain02 do?",
    "What capabilities does exchange01 have?",
    "Show me what agents can run PowerShell",
    "Which agents have Docker?",
    "What tools are available on domain02?",
    "List capabilities of ians-r16",
    "What's installed on the agents?",
    "Which machines can run Python?",
    "What server roles does domain02 have?",
    "Is domain02 a domain controller?",
    "What roles does exchange01 have?",
    
    # Multi-agent operations
    "Run this on all agents",
    "Execute on all machines",
    "Check all agents for disk space",
    "Run Get-Process on all agents",
    "Broadcast to all agents",
    "Run this everywhere",
    "Execute on every machine",
    "Check status on all hosts",
    
    # Drive/storage queries
    "What drives are available?",
    "List available drives",
    "What's on the C drive?",
    "What's on the D drive?",
    "Check the C: drive",
    "How much space on the C drive?",
    "What's on the external drive?",
    "List drives on my PC",
    "Show disk usage",
    "What's taking up space?",
    "Find large files on my computer",
    "Which files are biggest on my PC?",
    
    # =======================================================================
    # ADDITIONAL DEVELOPMENT TASKS
    # =======================================================================
    
    # Git operations
    "Commit my changes",
    "Push to origin",
    "Create a new branch",
    "Merge the feature branch",
    "Show git status",
    "Show me the git log",
    "Checkout the main branch",
    "Stage all changes",
    "Create a pull request",
    "Show the git diff",
    "Revert the last commit",
    "Cherry pick that commit",
    "Create a git tag",
    "Show branches",
    "Fetch from remote",
    
    # Docker operations
    "Build the Docker image",
    "Run the container",
    "Stop all containers",
    "List running containers",
    "Show Docker logs",
    "Remove stopped containers",
    "Pull the latest image",
    "Push the image to registry",
    "Show container stats",
    "Execute bash in container",
    "Restart the container",
    "Build with docker-compose",
    "Show Docker volumes",
    "Prune unused images",
    "Inspect the container",
    
    # Package management
    "Install this package",
    "Update all dependencies",
    "Remove unused packages",
    "Show outdated packages",
    "Add this to requirements.txt",
    "Install from package.json",
    "Update npm packages",
    "Install dev dependencies",
    "Lock dependencies",
    "Check for vulnerabilities",
    
    # Build and compile
    "Build the project",
    "Compile the code",
    "Run the build script",
    "Clean and rebuild",
    "Generate production build",
    "Watch for changes",
    "Hot reload the server",
    "Bundle the assets",
    "Minify the JavaScript",
    "Compile TypeScript",
    
    # Environment setup
    "Set up the virtual environment",
    "Install project dependencies",
    "Configure the database",
    "Set environment variables",
    "Initialize the project",
    "Create the config file",
    "Set up development environment",
    "Configure linting",
    "Initialize git repository",
    "Create project structure",
    
    # API and network
    "Make an API request",
    "Test the endpoint",
    "Call the REST API",
    "Send a POST request",
    "Check the API response",
    "Test authentication",
    "Verify the webhook",
    "Check the server status",
    "Test the connection",
    "Ping the service",
    
    # Database operations
    "Run database migrations",
    "Seed the database",
    "Query the database",
    "Update the schema",
    "Backup the database",
    "Restore from backup",
    "Show table structure",
    "Insert test data",
    "Delete old records",
    "Optimize the queries",
    
    # Testing
    "Run all tests",
    "Run unit tests",
    "Run integration tests",
    "Test coverage report",
    "Run specific test file",
    "Debug failing test",
    "Run e2e tests",
    "Generate test report",
    "Run tests in watch mode",
    "Test this component",
    
    # Documentation
    "Generate documentation",
    "Update the README",
    "Document this function",
    "Generate API docs",
    "Create usage examples",
    "Update changelog",
    "Write JSDoc comments",
    "Generate type definitions",
    "Create man page",
    "Update wiki page",
    
    # Deployment
    "Deploy to staging",
    "Deploy to production",
    "Release new version",
    "Rollback deployment",
    "Update the server",
    "Restart the service",
    "Scale up instances",
    "Configure load balancer",
    "Set up SSL certificate",
    "Update DNS records",
    
    # Monitoring and logging
    "Check the logs",
    "Show error logs",
    "Monitor the application",
    "Set up alerts",
    "Check metrics",
    "Debug the issue",
    "Trace the request",
    "Profile the code",
    "Analyze performance",
    "Check memory usage",
    
    # Security
    "Audit security",
    "Check for vulnerabilities",
    "Rotate credentials",
    "Update secrets",
    "Scan for malware",
    "Check permissions",
    "Review access logs",
    "Update firewall rules",
    "Generate SSL cert",
    "Encrypt the file",
]
